import type { Metadata } from 'next'
import './globals.css'
import { Navbar } from '@/components/Navbar'
import { ModalLogin } from '@/components/ModalLogin'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ModalLogin/>
        <div className="flex">
          <Navbar />
          <main className="w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
